export default {
  Register: 'تسجيل',
  Login: 'تسجيل دخول',
  Language: 'اللغة',
  'Select location': 'اختيار الموقع',
  'Select date': 'اختيار التاريخ',
  'Select time': 'اختيار الوقت',
  SR: 'ريال',
  'Service Provider List': 'قائمة مزودي الخدمة',
  'Select city': 'اختر مدينة',
  Place: 'المكان',
  Date: 'التاريخ',
  Time: 'الوقت',
  'Filter results': 'تصفية النتائج',
  Sort: 'التصنيف',
  'kitchen type': 'نوع المطبخ',
  'Restaurant type': 'نوع المطعم',
  'Highest price': 'السعر الأعلى',
  'Display by': 'عرض حسب',
  'View results': 'عرض النتائج',
  'Reset selection': 'مسح الاختيارات',
  Person: 'شخص',
  'Arrive at the site {{min}} minutes in advance for preparation':
    'الوصول للموقع قبل {{min}} دقيقة للتجهيز',
  extraPoints: 'نقاط إضافية يمكن لمزود الخدمة من إضافتها',
  addToOrder: 'إضافة إلى الطلب',
  'Total price': 'المبلغ الإجمالي',
  'Package added to order': 'تم إضافة الباقة للطلب',
  'Add more': 'إضافة المزيد',
  'Send order': 'إرسال الطلب',
  'Deliver Details': 'تفاصيل التوصيل',
  'Amount details': 'تفاصيل المبلغ',
  login: 'تسجيل الدخول',
  sendCode: 'إرسال الرمز',
  emailLogin: 'الدخول بالبريد',
  gotNoCode: 'لم يصلك رمز التحقق؟',
  resendCode: 'إعادة إرسال الرمز',
  enterPhone:
    'ادخل رقم جوالك لتسجيل الدخول، سيتم ارسال رسالة نصية للتحقق من الرقم المضاف.',
  enterCode: 'إدخل رمز التحقق المرسل على جوال رقم\n{{phone}}\n',
  'Enter Valid Phone Number': 'رجاء أدخل رقم هاتف سعودى صحيح',
  'Order Sent': 'تم إرسال الطلب بنجاح',
  'My Orders': 'طلباتي',
  'Service provider confirmation': 'تأكيد مزود الخدمة',
  'Complete payment': 'إكمال الدفع',
  'Pay now': 'إدفع الان',
  'Order details': 'بيانات الطلب',
  'Order status': 'حالة الطلب',
  'Order number': 'رقم الطلب',
  'Order date': 'تاريخ الطلب',
  'Contact information': 'بينات التواصل',
  'Total amount': 'إجمالي المبلغ',
  'Delivery details': 'تفاصيل التوصيل',
  'Service provider': 'مزود الخدمة',
  'My account': 'حسابي',
  Notifications: 'الاشعارات',
  'Technical support': 'الدعم الفنى',
  'About Cater': 'عن Cater',
  'Personal data': 'البيانات الشخصية',
  Email: 'البريد الإلكتروني',
  'Payment data': 'بيانات الدفع',
  'Sign out': 'تسجيل الخروج',
  'Contact us': 'اتصل بنا',
  'Live Chat': 'المحادثة المباشرة',
  'Write to us': 'راسلنا',
  'Connect with us': 'تواصل معنا',
  'Terms of Service': 'شروط الخدمة',
};
